import org.gradle.api.attributes.java.TargetJvmVersion

plugins {
    id 'java-library'
    id 'maven-publish'
}

base {
    archivesName = "${mod_id}-${project.name}-${minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
}

repositories {
    mavenCentral()

    exclusiveContent {
        forRepository {
            maven {
                name = 'Sponge'
                url = 'https://repo.spongepowered.org/repository/maven-public'
            }
        }
        filter { includeGroupAndSubgroups('org.spongepowered') }
    }

    exclusiveContent {
        forRepositories(
                maven {
                    name = 'ParchmentMC'
                    url = 'https://maven.parchmentmc.org/'
                },
                maven {
                    name = "NeoForge"
                    url = 'https://maven.neoforged.net/releases'
                }
        )
        filter { includeGroup('org.parchmentmc.data') }
    }
    maven {
        name = 'BlameJared'
        url = 'https://maven.blamejared.com'
    }
}

if (project.path.endsWith(":common")) {
    dependencies {
        compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
        compileOnly group: 'org.ow2.asm', name: 'asm-tree', version: '9.7.1'
        compileOnly 'org.jspecify:jspecify:1.0.0'

        compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.4.1'
        annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'

        compileOnly("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")

        modCompileOnly("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
        modCompileOnly("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")
        modCompileOnly("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}")
        compileOnly("com.tterrag.registrate:Registrate:${registrate_version}")

        compileOnly("foundry.veil:Veil-forge-${minecraft_version}:${project.veil_version}") {
            exclude group: "maven.modrinth"
            exclude group: "com.tterrag.registrate"
        }

        compileOnly("dev.ryanhcode.sable:sable-neoforge-1.21.1:${sable_version}") {
            transitive = false
            attributes {
                attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 21)
            }
        }
        compileOnly("dev.ryanhcode.sable-companion:sable-companion-common-1.21.1:${sable_companion_version}") {
            transitive = false
            attributes {
                attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 21)
            }
        }

        compileOnly("cc.tweaked:cc-tweaked-$minecraft_version-common-api:$computercraft_tweaked_version")
        compileOnly("maven.modrinth:sodium:$sodium_version")
        compileOnly("maven.modrinth:iris:$iris_version")
    }
}

['apiElements', 'runtimeElements', 'sourcesElements'].each { variant ->
    configurations."$variant".outgoing {
        capability("$group:${base.archivesName.get()}:$version")
        capability("$group:$mod_id-${project.name}-${minecraft_version}:$version")
        capability("$group:$mod_id:$version")
    }
    publishing.publications.configureEach {
        suppressPomMetadataWarningsFor(variant)
    }
}

sourcesJar {
    from(rootProject.file('LICENSE.md'))
}

jar {
    from(rootProject.file('LICENSE.md'))

    manifest {
        attributes([
                'Specification-Title'   : mod_name,
                'Specification-Vendor'  : mod_author,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : mod_author,
                'Built-On-Minecraft'    : minecraft_version,
                'MixinConfigs'          : "${mod_id}.mixins.json"
        ])
    }
}

processResources {
    var expandProps = [
            'version'                      : version,
            'group'                        : project.group,
            'minecraft_version'            : minecraft_version,
            'minecraft_version_range'      : minecraft_version_range,
            'fabric_version'               : fabric_version,
            'fabric_loader_version'        : fabric_loader_version,
            'mod_name'                     : mod_name,
            'mod_author'                   : mod_author,
            'mod_id'                       : mod_id,
            'license'                      : license,
            'description'                  : project.description,
            'neoforge_version'             : neoforge_version,
            'neoforge_loader_version_range': neoforge_loader_version_range,
            'forge_version'                : forge_version,
            'forge_loader_version_range'   : forge_loader_version_range,
            'sable_mod_version_range'      : sable_mod_version_range,
            'create_mod_version'           : create_mod_version,
            'flywheel_mod_version'         : flywheel_mod_version,
            'credits'                      : credits,
            'java_version'                 : java_version,
            'forgeconfigapiport_version'   : project.findProperty('forgeconfigapiport_version') ?: '',
            'veil_version'                 : project.findProperty('veil_version') ?: '',
            'modmenu_version'              : project.findProperty('modmenu_version') ?: ''
    ]

    filesMatching(['pack.mcmeta', 'fabric.mod.json', 'META-INF/mods.toml', 'META-INF/neoforge.mods.toml', '*.mixins.json']) {
        expand expandProps
    }
    inputs.properties(expandProps)
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url = System.getenv('local_maven_url')

            credentials {
                username = System.getenv('local_maven_user')
                password = System.getenv('local_maven_token')
            }

            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}
