plugins {
    id 'multiloader-common'
}

configurations {
    commonJava {
        canBeResolved = true
    }
    commonResources {
        canBeResolved = true
    }
}

dependencies {
    def commonProjectPath = project.path.contains(':') ? ":${project.parent.name}:common" : ':common'

    compileOnly(project(commonProjectPath)) {
        capabilities {
            requireCapability "$group:$mod_id"
        }
    }
    commonJava project(path: commonProjectPath, configuration: 'commonJava')
    commonResources project(path: commonProjectPath, configuration: 'commonResources')
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava)
    from(configurations.commonJava)
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}
