import org.gradle.api.attributes.java.TargetJvmVersion

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    modApi("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")

    modApi("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    modApi("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")
    modCompileOnly("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}")
    modImplementation("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}")
    compileOnly("com.tterrag.registrate:Registrate:${registrate_version}")

    modImplementation("foundry.veil:Veil-forge-${minecraft_version}:${project.veil_version}") {
        exclude group: "maven.modrinth"
    }

    compileOnly("dev.ryanhcode.sable:sable-neoforge-1.21.1:${sable_version}") {
        transitive = false
        attributes {
            attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 21)
        }
    }

    compileOnly("cc.tweaked:cc-tweaked-$minecraft_version-core-api:$computercraft_tweaked_version")
    compileOnly("cc.tweaked:cc-tweaked-$minecraft_version-forge-api:$computercraft_tweaked_version")

    compileOnly("maven.modrinth:iris:$iris_version")
    compileOnly("maven.modrinth:sodium:$rootProject.sodium_version")
}
