plugins {
    id 'net.neoforged.moddev.legacyforge'
}

def forgeProjects = rootProject.subprojects.findAll { it.path.endsWith(":neoforge") }

forgeProjects.each { forgeProject ->
    evaluationDependsOn(forgeProject.path)
}

legacyForge {
    version = forge_full_version

    forgeProjects.forEach { forgeProject ->
        def parentName = forgeProject.parent.name
        def commonProject = project(":$parentName:common")
        def at = commonProject.file('src/main/resources/META-INF/accesstransformer.cfg')

        if (at.exists()) {
            accessTransformers.from(at.absolutePath)
        }
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            ideName = "Forge ${it.name.capitalize()} (${project.path})"
        }

        client {
            client()
            gameDirectory = project.file('runs/client')
        }

        server {
            server()
            gameDirectory = project.file('runs/server')
            programArgument 'nogui'
        }
    }

    mods {
        forgeProjects.forEach { forgeProject ->
            def parentName = forgeProject.parent.name
            "$parentName" {
                sourceSet forgeProject.sourceSets.main
            }
        }
    }
}

tasks.register("runDataAll") {
    group = "mod development"
    forgeProjects.forEach { forgeProject ->
        dependsOn(forgeProject.tasks.runData)
    }
}

dependencies {
    forgeProjects.forEach {
        def parentName = it.parent.name
        implementation(it) {
            capabilities {
                requireCapability "$group:${parentName}"
            }
        }
    }
}
