plugins {
    id 'net.neoforged.moddev.legacyforge'
    id 'multiloader-loader'
    id 'multiloader-neoforge'
}

evaluationDependsOn(':simulated:neoforge')

def generatedResources = project(":aeronautics:common").file("src/generated/resources")
def commonResources = project(":aeronautics:common").file("src/main/resources")

legacyForge {
    version = forge_full_version

    def at = project(':aeronautics:common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            ideName = "Aero Forge ${it.name.capitalize()} (${project.path})"
        }

        data {
            data()
            gameDirectory = project.file('runs/data')
            programArguments.addAll '--all',
                    '--mod', 'aeronautics',
                    '--output', generatedResources.absolutePath,
                    '--existing', commonResources.absolutePath,
                    '--existing-mod', 'create',
                    '--existing-mod', 'simulated'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
        simulated {
            sourceSet project(':simulated:neoforge').sourceSets.main
        }
    }
}

sourceSets.main.resources {
    srcDir generatedResources.absolutePath
}
